FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["HabitTracker.sln", "./"]
COPY ["src/CoreService/CoreService.Api/CoreService.Api.csproj", "src/CoreService/CoreService.Api/"]
COPY ["src/CoreService/CoreService.Application/CoreService.Application.csproj", "src/CoreService/CoreService.Application/"]
COPY ["src/CoreService/CoreService.Domain/CoreService.Domain.csproj", "src/CoreService/CoreService.Domain/"]
COPY ["src/CoreService/CoreService.Infrastructure/CoreService.Infrastructure.csproj", "src/CoreService/CoreService.Infrastructure/"]

RUN dotnet restore "src/CoreService/CoreService.Api/CoreService.Api.csproj"

COPY . .
RUN dotnet publish "src/CoreService/CoreService.Api/CoreService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CoreService.Api.dll"]
