<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Commands\" />
      <Folder Include="Exceptions\" />
      <Folder Include="Handlers\" />
      <Folder Include="Interfaces\" />
      <Folder Include="Queries\" />
      <Folder Include="Responses\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CoreService.Domain\CoreService.Domain.csproj" />
    </ItemGroup>

</Project>
